### ISSUE TITLE
PrivateKeyNotFound when key already exists.

### ISSUE THREAD

**Issue by JimitSoni18** [BiagioFesta/wtransport#151]
I am trying to get started with the wtransport crate, I generated pem certificate and private key using openssl using the following command:

```bash
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365
```

which generated 
`
-rw-rw-r--  1 my_username my_username 2122 Mar 29 12:33 cert.pem
-rw-------  1 my_username my_username 3422 Mar 29 12:30 key.pem
`
in the directory `/home/my_username/cert/`

then I copied the same code as it is in the docs: 

```rust
use wtransport::{Endpoint, Identity, ServerConfig};

#[tokio::main]
async fn main() {
	let config = ServerConfig::builder()
		.with_bind_default(4433)
		.with_identity(
			&Identity::load_pemfiles("/home/my_username/cert/cert.pem", "/home/my_username/cert/key.pem")
				.await
				.unwrap(),
		)
		.build();

	let server = Endpoint::server(config).unwrap();

	loop {
		let incoming_session = server.accept().await;
		let incoming_req = incoming_session.await.unwrap();

		let connection = incoming_req.accept().await.unwrap();

		println!("=>> connection: {connection:?}");
	}
}

```

but when I try to run it using cargo r, it gives me the following error:

wt on  master [?] is 📦 v0.1.0 via 🦀 v1.76.0
❯ cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/wt`
thread 'main' panicked at src/main.rs:10:18:
called `Result::unwrap()` on an `Err` value: PrivateKeyNotFound
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I know that the file is present there, because loading cert.pem did not unwrap, so I don't know what I did wrong.

please help

**Comment by JimitSoni18** [comment]
here is my cargo toml:

```toml
[package]
name = "wt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
wtransport = "0.1.12"
```
